In [1]:
import numpy as np
def position_1D(dimension,pos):
    assert dimension%2==0
    omega=np.arange(dimension//2,dtype=float)
    print(omega)
    omega/=dimension/2.
    omega=1./10000**omega
    print(omega)
    pos=pos.reshape(-1)
    out=np.einsum('m,d->md',pos,omega)
    print(out)
    Sin_out=np.sin(out)
    Cos_out=np.cos(out)
    embedding=np.concatenate([Sin_out,Cos_out],axis=1)
    return embedding
def position_2D(dimension,grid):
    embed_H=position_1D(dimension//2,grid[0])
    embed_W=position_1D(dimension//2,grid[1])
    embeding=np.concatenate([embed_H,embed_W],axis=1)
    return embeding


In [2]:
import numpy as np

# Grid size (height and width of the grid)
grid_size = 5

# Create arrays representing the height and width of the grid
grid_h = np.arange(grid_size, dtype=np.float32)
grid_w = np.arange(grid_size, dtype=np.float32)

print("grid_h:")
print(grid_h)
print("grid_w:")
print(grid_w)

# Generate a coordinate grid
grid = np.meshgrid(grid_w, grid_h)  # Here width goes first

print("After meshgrid:")
print("grid[0] (X coordinates):")
#print(grid[0][0])  # X coordinates
print("grid[1] (Y coordinates):")
#print(grid[1])  # Y coordinates

# Stack these two arrays along a new axis
stacked_grid = np.stack(grid, axis=0)
#stacked_grid=stacked_grid.reshape(2,1,5,5)
print("Stacked grid:")
#print(stacked_grid)

print("Stacked grid shape:", stacked_grid.shape)
print('pos',position_1D(2,stacked_grid[0]))


grid_h:
[0. 1. 2. 3. 4.]
grid_w:
[0. 1. 2. 3. 4.]
After meshgrid:
grid[0] (X coordinates):
grid[1] (Y coordinates):
Stacked grid:
Stacked grid shape: (2, 5, 5)
[0.]
[1.]
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]]
pos [[ 0.          1.        ]
 [ 0.84147098  0.54030231]
 [ 0.90929743 -0.41614684]
 [ 0.14112001 -0.9899925 ]
 [-0.7568025  -0.65364362]
 [ 0.          1.        ]
 [ 0.84147098  0.54030231]
 [ 0.90929743 -0.41614684]
 [ 0.14112001 -0.9899925 ]
 [-0.7568025  -0.65364362]
 [ 0.          1.        ]
 [ 0.84147098  0.54030231]
 [ 0.90929743 -0.41614684]
 [ 0.14112001 -0.9899925 ]
 [-0.7568025  -0.65364362]
 [ 0.          1.        ]
 [ 0.84147098  0.54030231]
 [ 0.90929743 -0.41614684]
 [ 0.14112001 -0.9899925 ]
 [-0.7568025  -0.65364362]
 [ 0.          1.        ]
 [ 0.84147098  0.54030231]
 [ 0.90929743 -0.41614684]
 [ 0.14112001 -0.9899925 ]
 [-0.7568025  -0.65364362]]

In [3]:
position_1D(2,stacked_grid[0])

[0.]
[1.]
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]]


array([[ 0.        ,  1.        ],
       [ 0.84147098,  0.54030231],
       [ 0.90929743, -0.41614684],
       [ 0.14112001, -0.9899925 ],
       [-0.7568025 , -0.65364362],
       [ 0.        ,  1.        ],
       [ 0.84147098,  0.54030231],
       [ 0.90929743, -0.41614684],
       [ 0.14112001, -0.9899925 ],
       [-0.7568025 , -0.65364362],
       [ 0.        ,  1.        ],
       [ 0.84147098,  0.54030231],
       [ 0.90929743, -0.41614684],
       [ 0.14112001, -0.9899925 ],
       [-0.7568025 , -0.65364362],
       [ 0.        ,  1.        ],
       [ 0.84147098,  0.54030231],
       [ 0.90929743, -0.41614684],
       [ 0.14112001, -0.9899925 ],
       [-0.7568025 , -0.65364362],
       [ 0.        ,  1.        ],
       [ 0.84147098,  0.54030231],
       [ 0.90929743, -0.41614684],
       [ 0.14112001, -0.9899925 ],
       [-0.7568025 , -0.65364362]])

In [4]:
dimension = 4
grid1= np.array([[[0, 1], [0, 1]], [[0, 0], [1, 1]]])  # shape (2, 2, 2)

# Process the grid along the height (axis 0)
embed_H=position_1D(dimension//2,grid[0])
print("Embedding for Height:")
print(embed_H)

# Process the grid along the width (axis 1)
embed_W=position_1D(dimension//2,grid[1])
print("\nEmbedding for Width:")
print(embed_W)

# Combine the height and width embeddings
embedding=np.concatenate([embed_H,embed_W],axis=1)
print("\nFinal 2D Position Embedding:")
print(embedding)


[0.]
[1.]
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]]
Embedding for Height:
[[ 0.          1.        ]
 [ 0.84147098  0.54030231]
 [ 0.90929743 -0.41614684]
 [ 0.14112001 -0.9899925 ]
 [-0.7568025  -0.65364362]
 [ 0.          1.        ]
 [ 0.84147098  0.54030231]
 [ 0.90929743 -0.41614684]
 [ 0.14112001 -0.9899925 ]
 [-0.7568025  -0.65364362]
 [ 0.          1.        ]
 [ 0.84147098  0.54030231]
 [ 0.90929743 -0.41614684]
 [ 0.14112001 -0.9899925 ]
 [-0.7568025  -0.65364362]
 [ 0.          1.        ]
 [ 0.84147098  0.54030231]
 [ 0.90929743 -0.41614684]
 [ 0.14112001 -0.9899925 ]
 [-0.7568025  -0.65364362]
 [ 0.          1.        ]
 [ 0.84147098  0.54030231]
 [ 0.90929743 -0.41614684]
 [ 0.14112001 -0.9899925 ]
 [-0.7568025  -0.65364362]]
[0.]
[1.]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [4.]
 [4.]

In [5]:
grid1[0][0]

array([0, 1])

In [6]:
def get_2d_position_from_start(embed_dim,grid_size):
    grid_height=np.arange(grid_size,dtype=np.float32)
    grid_width=np.arange(grid_size,dtype=np.float32)
    grid=np.meshgrid(grid_width,grid_height)
    grid=np.stack(grid,axis=0)
    position=position_2D(embed_dim,grid)
    return position

In [7]:
def relative_position(embed_dim,grid_size):
    pos_embedding=get_2d_position_from_start(embed_dim,grid_size)
    relative_position=2*np.matmul(pos_embedding,pos_embedding.transpose())/pos_embedding.shape[1]
    return relative_position

In [8]:
relative_position(4,5)

[0.]
[1.]
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [0.]
 [1.]
 [2.]
 [3.]
 [4.]]
[0.]
[1.]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [4.]
 [4.]
 [4.]
 [4.]
 [4.]]


array([[ 1.        ,  0.77015115,  0.29192658,  0.00500375,  0.17317819,
         0.77015115,  0.54030231,  0.06207773, -0.2248451 , -0.05667066,
         0.29192658,  0.06207773, -0.41614684, -0.70306967, -0.53489523,
         0.00500375, -0.2248451 , -0.70306967, -0.9899925 , -0.82181806,
         0.17317819, -0.05667066, -0.53489523, -0.82181806, -0.65364362],
       [ 0.77015115,  1.        ,  0.77015115,  0.29192658,  0.00500375,
         0.54030231,  0.77015115,  0.54030231,  0.06207773, -0.2248451 ,
         0.06207773,  0.29192658,  0.06207773, -0.41614684, -0.70306967,
        -0.2248451 ,  0.00500375, -0.2248451 , -0.70306967, -0.9899925 ,
        -0.05667066,  0.17317819, -0.05667066, -0.53489523, -0.82181806],
       [ 0.29192658,  0.77015115,  1.        ,  0.77015115,  0.29192658,
         0.06207773,  0.54030231,  0.77015115,  0.54030231,  0.06207773,
        -0.41614684,  0.06207773,  0.29192658,  0.06207773, -0.41614684,
        -0.70306967, -0.2248451 ,  0.00500375, -0

In [9]:
import torch
from torch import nn
import math

/home/accl-ros/.local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [10]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [11]:
def pairwise_distance(x):
    """
    Compute pairwise distance of a point cloud.
    Args:
        x: tensor (batch_size, num_points, num_dims)
    Returns:
        pairwise distance: (batch_size, num_points, num_points)
    """
    with torch.no_grad():
        x_inner = -2*torch.matmul(x, x.transpose(2, 1))
        x_square = torch.sum(torch.mul(x, x), dim=-1, keepdim=True)
        return x_square + x_inner + x_square.transpose(2, 1)


def part_pairwise_distance(x, start_idx=0, end_idx=1):
    """
    Compute pairwise distance of a point cloud.
    Args:
        x: tensor (batch_size, num_points, num_dims)
    Returns:
        pairwise distance: (batch_size, num_points, num_points)
    """
    with torch.no_grad():
        x_part = x[:, start_idx:end_idx]
        x_square_part = torch.sum(torch.mul(x_part, x_part), dim=-1, keepdim=True)
        x_inner = -2*torch.matmul(x_part, x.transpose(2, 1))
        x_square = torch.sum(torch.mul(x, x), dim=-1, keepdim=True)
        return x_square_part + x_inner + x_square.transpose(2, 1)


def xy_pairwise_distance(x, y):
    """
    Compute pairwise distance of a point cloud.
    Args:
        x: tensor (batch_size, num_points, num_dims)
    Returns:
        pairwise distance: (batch_size, num_points, num_points)
    """
    with torch.no_grad():
        xy_inner = -2*torch.matmul(x, y.transpose(2, 1))
        x_square = torch.sum(torch.mul(x, x), dim=-1, keepdim=True)
        y_square = torch.sum(torch.mul(y, y), dim=-1, keepdim=True)
        return x_square + xy_inner + y_square.transpose(2, 1)

In [12]:
def dense_knn_matrix(x,k=16,relative_position=None):
    with torch.no_grad():
        x=x.transpose(2,1).squeeze(-1)
        batch_size,n_points,n_dims=x.shape
        n_part=10000

        if n_points>n_part:
            nn_idsx_list=[]
            groups=math.ceil(n_points/n_part)
            for i in range (groups):
                start_idx=n_part*i
                end_idx=min(n_points,n_part*(i+1))
                distance=part_pairwise_distance(x.detach(),start_idx,end_idx)
                if relative_position is not None:
                    distance+=relative_position[:,start_idx:end_idx]
                _,nn_idx_part=torch.topk(-distance,k=k)
                nn_idx_list+=[nn.idx_list]
            nn_idx=torch.cat(nn_idsx_list,dim=1)
        else:
            distance=pairwise_distance(x.detach())
            if relative_position is not None:
                distance+=relative_position
                _,nn_idx=torch.topk(-distance,k=k)
        center_idx = torch.arange(0, n_points, device=x.device).repeat(batch_size, k, 1).transpose(2, 1)
        return torch.stack((nn_idx,center_idx),dim=0)
def xy_dense_knn_matrix(x, y, k=16, relative_pos=None):

    with torch.no_grad():
            x = x.transpose(2, 1).squeeze(-1)
            y = y.transpose(2, 1).squeeze(-1)
            batch_size, n_points, n_dims = x.shape
            dist = xy_pairwise_distance(x.detach(), y.detach())
            if relative_pos is not None:
                dist += relative_pos
            _, nn_idx = torch.topk(-dist, k=k)
            center_idx = torch.arange(0, n_points, device=x.device).repeat(batch_size, k, 1).transpose(2, 1)
    return torch.stack((nn_idx, center_idx), dim=0)


In [13]:
class DenseDilated(nn.Module):
    def __init__(self,k=9,dilation=9,stochastic=False,epsilon=0.0):
        super(DenseDilated, self).__init__()
        self.dilation = dilation
        self.stochastic = stochastic
        self.epsilon = epsilon
        self.k = k
    def forward(self,edge_index):
        if self.stochastic:
            if torch.rand(1) < self.epsilon and self.training:
                num=self.k*self.dilation
                randnum=torch.randperm(num)[:self.k]
                edge_index=edge_index[:,:,:,randnum]
            else:
                edge_index=edge_index[:,:,:,::self.dilation]
        else:
            edge_index=edge_index[:,:,:,::self.dilation]
        return edge_index

class DenseDilatedKnnGraph(nn.Module):
    """
    Find the neighbors' indices based on dilated knn
    """
    def __init__(self, k=9, dilation=1, stochastic=False, epsilon=0.0):
        super(DenseDilatedKnnGraph, self).__init__()
        self.dilation = dilation
        self.stochastic = stochastic
        self.epsilon = epsilon
        self.k = k
        self._dilated = DenseDilated(k, dilation, stochastic, epsilon)

    def forward(self, x, y=None, relative_pos=None):
        if y is not None:
            #### normalize
            x = F.normalize(x, p=2.0, dim=1)
            y = F.normalize(y, p=2.0, dim=1)
            ####
            edge_index = xy_dense_knn_matrix(x, y, self.k * self.dilation, relative_pos)
        else:
            #### normalize
            x = F.normalize(x, p=2.0, dim=1)
            ####
            edge_index = dense_knn_matrix(x, self.k * self.dilation, relative_pos)
        return self._dilated(edge_index)

In [14]:
from torch.nn import Sequential as Seq, Linear as Lin, Conv2d

In [15]:
def act_layer(act, inplace=False, neg_slope=0.2, n_prelu=1):
    # activation layer

    act = act.lower()
    if act == 'relu':
        layer = nn.ReLU(inplace)
    elif act == 'leakyrelu':
        layer = nn.LeakyReLU(neg_slope, inplace)
    elif act == 'prelu':
        layer = nn.PReLU(num_parameters=n_prelu, init=neg_slope)
    elif act == 'gelu':
        layer = nn.GELU()
    elif act == 'hswish':
        layer = nn.Hardswish(inplace)
    else:
        raise NotImplementedError('activation layer [%s] is not found' % act)
    return layer
def norm_layer(norm, nc):
    # normalization layer 2d
    norm = norm.lower()
    if norm == 'batch':
        layer = nn.BatchNorm2d(nc, affine=True)
    elif norm == 'instance':
        layer = nn.InstanceNorm2d(nc, affine=False)
    else:
        raise NotImplementedError('normalization layer [%s] is not found' % norm)
    return layer
class BasicConv(Seq):
    def __init__(self, channels, act='relu', norm=None, bias=True, drop=0.):
        m = []
        for i in range(1, len(channels)):
            m.append(Conv2d(channels[i - 1], channels[i], 1, bias=bias, groups=4))
            if norm is not None and norm.lower() != 'none':
                m.append(norm_layer(norm, channels[-1]))
            if act is not None and act.lower() != 'none':
                m.append(act_layer(act))
            if drop > 0:
                m.append(nn.Dropout2d(drop))

        super(BasicConv, self).__init__(*m)

        self.reset_parameters()

    def reset_parameters(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, nn.BatchNorm2d) or isinstance(m, nn.InstanceNorm2d):
                m.weight.data.fill_(1)
                m.bias.data.zero_()
def batched_index_select(x, idx):
    r"""fetches neighbors features from a given neighbor idx

    Args:
        x (Tensor): input feature Tensor
                :math:`\mathbf{X} \in \mathbb{R}^{B \times C \times N \times 1}`.
        idx (Tensor): edge_idx
                :math:`\mathbf{X} \in \mathbb{R}^{B \times N \times l}`.
    Returns:
        Tensor: output neighbors features
            :math:`\mathbf{X} \in \mathbb{R}^{B \times C \times N \times k}`.
    """
    batch_size, num_dims, num_vertices_reduced = x.shape[:3]
    _, num_vertices, k = idx.shape
    idx_base = torch.arange(0, batch_size, device=idx.device).view(-1, 1, 1) * num_vertices_reduced
    idx = idx + idx_base
    idx = idx.contiguous().view(-1)

    x = x.transpose(2, 1)
    feature = x.contiguous().view(batch_size * num_vertices_reduced, -1)[idx, :]
    feature = feature.view(batch_size, num_vertices, k, num_dims).permute(0, 3, 1, 2).contiguous()
    return feature

In [16]:
from torchvision.models import resnet50

class BasicConv(Seq):
    def __init__(self, channels, act='relu', norm=None, bias=True, drop=0.):
        m = []
        for i in range(1, len(channels)):
            m.append(Conv2d(channels[i - 1], channels[i], 1, bias=bias, groups=4))
            if norm is not None and norm.lower() != 'none':
                m.append(norm_layer(norm, channels[-1]))
            if act is not None and act.lower() != 'none':
                m.append(act_layer(act))
            if drop > 0:
                m.append(nn.Dropout2d(drop))

        super(BasicConv, self).__init__(*m)

        self.reset_parameters()

    def reset_parameters(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight)
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
            elif isinstance(m, nn.BatchNorm2d) or isinstance(m, nn.InstanceNorm2d):
                m.weight.data.fill_(1)
                m.bias.data.zero_()



In [17]:
class Max_relative(nn.Module):

    def __init__(self, in_channels, out_channels, act='relu', norm=None, bias=True):
        super(Max_relative,self).__init__()
        self.conv1=BasicConv([in_channels*2,out_channels],act, norm, bias)
    def forward(self,x,edge_index,y=None):
        x_i=batched_index_select(x,edge_index[1])
        if y is not None:
            x_j = batched_index_select(y, edge_index[0])
        else:
            x_j = batched_index_select(x, edge_index[0])
        x_j,_=torch.max(x_j-x_i,-1, keepdim=True)
        b, c, n, _ = x.shape
        x = torch.cat([x.unsqueeze(2), x_j.unsqueeze(2)], dim=2).reshape(b, 2 * c, n, _)
        return self.conv1(x)

class EdgeConv2d(nn.Module):
    """
    Edge convolution layer (with activation, batch normalization) for dense data type
    """
    def __init__(self, in_channels, out_channels, act='relu', norm=None, bias=True):
        super(EdgeConv2d, self).__init__()
        self.nn = BasicConv([in_channels * 2, out_channels], act, norm, bias)

    def forward(self, x, edge_index, y=None):
        x_i = batched_index_select(x, edge_index[1])
        if y is not None:
            x_j = batched_index_select(y, edge_index[0])
        else:
            x_j = batched_index_select(x, edge_index[0])
        max_value, _ = torch.max(self.nn(torch.cat([x_i, x_j - x_i], dim=1)), -1, keepdim=True)
        return max_value


class GraphSAGE(nn.Module):
    """
    GraphSAGE Graph Convolution (Paper: https://arxiv.org/abs/1706.02216) for dense data type
    """
    def __init__(self, in_channels, out_channels, act='relu', norm=None, bias=True):
        super(GraphSAGE, self).__init__()
        self.nn1 = BasicConv([in_channels, in_channels], act, norm, bias)
        self.nn2 = BasicConv([in_channels*2, out_channels], act, norm, bias)

    def forward(self, x, edge_index, y=None):
        if y is not None:
            x_j = batched_index_select(y, edge_index[0])
        else:
            x_j = batched_index_select(x, edge_index[0])
        x_j, _ = torch.max(self.nn1(x_j), -1, keepdim=True)
        return self.nn2(torch.cat([x, x_j], dim=1))


class GINConv2d(nn.Module):
    """
    GIN Graph Convolution (Paper: https://arxiv.org/abs/1810.00826) for dense data type
    """
    def __init__(self, in_channels, out_channels, act='relu', norm=None, bias=True):
        super(GINConv2d, self).__init__()
        self.nn = BasicConv([in_channels, out_channels], act, norm, bias)
        eps_init = 0.0
        self.eps = nn.Parameter(torch.Tensor([eps_init]))

    def forward(self, x, edge_index, y=None):
        if y is not None:
            x_j = batched_index_select(y, edge_index[0])
        else:
            x_j = batched_index_select(x, edge_index[0])
        x_j = torch.sum(x_j, -1, keepdim=True)
        return self.nn((1 + self.eps) * x + x_j)


class GraphConv2d(nn.Module):
    """
    Static graph convolution layer
    """
    def __init__(self, in_channels, out_channels, conv='mr', act='relu', norm=None, bias=True):
        super(GraphConv2d, self).__init__()
        if conv == 'edge':
            self.gconv = EdgeConv2d(in_channels, out_channels, act, norm, bias)
        elif conv == 'mr':
            self.gconv = Max_relative(in_channels, out_channels, act, norm, bias)
        elif conv == 'sage':
            self.gconv = GraphSAGE(in_channels, out_channels, act, norm, bias)
        elif conv == 'gin':
            self.gconv = GINConv2d(in_channels, out_channels, act, norm, bias)
        else:
            raise NotImplementedError('conv:{} is not supported'.format(conv))

    def forward(self, x, edge_index, y=None):
        return self.gconv(x, edge_index, y)


In [18]:
import torch.nn.functional as F

In [19]:
class Dynamic_graph(GraphConv2d):
    def __init__(self,in_channels, out_channels, kernel_size=9, dilation=1, conv='mr', act='relu',
                 norm=None, bias=True, stochastic=False, epsilon=0.0, r=1):
        super(Dynamic_graph,self).__init__(in_channels,out_channels,conv,act,norm,bias)
        self.k=kernel_size
        self.d=dilation
        self.r=r
        self.knn_graph=DenseDilatedKnnGraph(kernel_size,dilation,stochastic,epsilon)
    def forward(self,x,relative_position=None):
        B,C,H,W=x.shape
        y=None
        if self.r > 1:
            y = F.avg_pool2d(x, self.r, self.r)
            y = y.reshape(B, C, -1, 1).contiguous()
        x=x.reshape(B,C,-1,1).contiguous()
        edge_index=self.knn_graph(x,y,relative_position)
        x=super(Dynamic_graph,self).forward(x,edge_index,y)
        return x.reshape(B, -1, H, W).contiguous()

In [20]:
pip install git+https://github.com/rwightman/pytorch-image-models.git

  Cloning https://github.com/rwightman/pytorch-image-models.git to /tmp/pip-req-build-h6avjc_8
  Running command git clone --filter=blob:none --quiet https://github.com/rwightman/pytorch-image-models.git /tmp/pip-req-build-h6avjc_8


  Resolved https://github.com/rwightman/pytorch-image-models.git to commit 4224529ebe6b74c7521ad00e378fced84cdb2f6d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for timm: filename=timm-0.9.5-py3-none-any.whl size=2187147 sha256=3e483c808f6c0c0e2b264db24461ea27eff9bb1cf855eba8839b183cc4555b3d
  Stored in directory: /tmp/pip-ephem-wheel-cache-ma9javy7/wheels/ed/07/8c/d16ff40e1a6ab5eff4240181152d83e10a933e1973397a1fec
Successfully built timm
  Attempting uninstall: timm
    Found existing installation: timm 0.9.3.dev0
    Uninstalling timm-0.9.3.dev0:
      Successfully uninstalled timm-0.9.3.dev0
Note: you may need to restart the kernel to use updated packages.


In [21]:
from timm.models.layers import DropPath

In [22]:
class  Grapher(nn.Module):
    def __init__(self,in_channels, kernel_size=9, dilation=1, conv='mr', act='relu', norm=None,
                 bias=True,  stochastic=False, epsilon=0.0, r=1, n=196, drop_path=0.0, relative_pos=False) :
        super(Grapher,self).__init__()
        self.channels = in_channels
        self.n = n
        self.r = r
        self.fc1 = nn.Sequential(
            nn.Conv2d(in_channels, in_channels, 1, stride=1, padding=0),
            nn.BatchNorm2d(in_channels),
        )
        self.graph_conv = Dynamic_graph(in_channels, in_channels * 2, kernel_size, dilation, conv,
                              act, norm, bias, stochastic, epsilon, r)
        self.fc2 = nn.Sequential(
            nn.Conv2d(in_channels * 2, in_channels, 1, stride=1, padding=0),
            nn.BatchNorm2d(in_channels),
        )
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.relative_pos = None
        if relative_pos :
            print('using relative pos')
            relative_pos_tensor=torch.from_numpy(np.float32(relative_position(in_channels,int(n**0.5)))).unsqueeze(0).unsqueeze(1)
            relative_pos_tensor = F.interpolate(
                    relative_pos_tensor, size=(n, n//(r*r)), mode='bicubic', align_corners=False)
            self.relative_pos=nn.Parameter(-relative_pos_tensor.squeeze(1),requires_grad=False)
    def _get_relative_pos(self, relative_pos, H, W):
        if relative_pos is None or H * W == self.n:
            return relative_pos
        else:
            N = H * W
            N_reduced = N // (self.r * self.r)
            return F.interpolate(relative_pos.unsqueeze(0), size=(N, N_reduced), mode="bicubic").squeeze(0)

    def forward(self, x):
        _tmp = x
        x = self.fc1(x)
        B, C, H, W = x.shape
        relative_pos = self._get_relative_pos(self.relative_pos, H, W)
        x = self.graph_conv(x, relative_pos)
        x = self.fc2(x)
        x = self.drop_path(x) + _tmp
        return x

In [23]:
class FFN(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act='relu', drop_path=0.0):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features
        self.fc1 = nn.Sequential(
            nn.Conv2d(in_features, hidden_features, 1, stride=1, padding=0),
            nn.BatchNorm2d(hidden_features),
        )
        self.act = act_layer(act)
        self.fc2 = nn.Sequential(
            nn.Conv2d(hidden_features, out_features, 1, stride=1, padding=0),
            nn.BatchNorm2d(out_features),
        )
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()

    def forward(self, x):
        shortcut = x
        x = self.fc1(x)
        x = self.act(x)
        x = self.fc2(x)
        x = self.drop_path(x) + shortcut
        return x

In [24]:
class Stem(nn.Module):
    def __init__(self, img_size=224, in_dim=3, out_dim=768, act='relu'):
        super().__init__()
        self.convs = nn.Sequential(
            nn.Conv2d(in_dim, out_dim//2, 3, stride=2, padding=1),
            nn.BatchNorm2d(out_dim//2),
            act_layer(act),
            nn.Conv2d(out_dim//2, out_dim, 3, stride=2, padding=1),
            nn.BatchNorm2d(out_dim),
            act_layer(act),
            nn.Conv2d(out_dim, out_dim, 3, stride=1, padding=1),
            nn.BatchNorm2d(out_dim),
        )

    def forward(self, x):
        x = self.convs(x)
        return x
class Downsample(nn.Module):

    def __init__(self, in_dim=3, out_dim=768):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_dim, out_dim, 3, stride=2, padding=1),
            nn.BatchNorm2d(out_dim),
        )

    def forward(self, x):
        x = self.conv(x)
        return x


In [25]:
from torch.nn import Sequential as Seq

from timm.data import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD
from timm.models.helpers import load_pretrained
from timm.models.layers import DropPath, to_2tuple, trunc_normal_
from timm.models.registry import register_model

def _cfg(url='', **kwargs):
    return {
        'url': url,
        'num_classes': 1000, 'input_size': (3, 224, 224), 'pool_size': None,
        'crop_pct': .9, 'interpolation': 'bicubic',
        'mean': IMAGENET_DEFAULT_MEAN, 'std': IMAGENET_DEFAULT_STD,
        'first_conv': 'patch_embed.proj', 'classifier': 'head',
        **kwargs
    }


default_cfgs = {
    'vig_224_gelu': _cfg(
        mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5),
    ),
    'vig_b_224_gelu': _cfg(
        crop_pct=0.95, mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5),
    ),
}
class DeepGCN(torch.nn.Module):
    def __init__(self, opt):
        super(DeepGCN, self).__init__()
        print(opt)
        k = opt.k
        act = opt.act
        norm = opt.norm
        bias = opt.bias
        epsilon = opt.epsilon
        stochastic = opt.use_stochastic
        conv = opt.conv
        emb_dims = opt.emb_dims
        drop_path = opt.drop_path

        blocks = opt.blocks
        self.n_blocks=sum(blocks)
        channels = opt.channels
        reduce_ratios = [4, 2, 1, 1]
        drop_path_rate=[x.item() for x in torch.linspace(0,drop_path,self.n_blocks)]
        num_knn=[int(x.item()) for x in torch.linspace(k,k,self.n_blocks) ]
        max_dilation=49//max(num_knn)
        self.stem=Stem(out_dim=channels[0],act=act)
        self.pos_embed=nn.Parameter(torch.zeros(1,channels[0],224//4,224//4))

        HW=224 // 4 * 224 // 4
        self.backbone=nn.ModuleList([])
        idx=0
        for i in range (len(blocks)):
            if i>0:
                self.backbone.append(Downsample(channels[i-1],channels[i]))
                HW=HW//4
            for j in range (blocks[i]):
                self.backbone.append (Seq(Grapher(channels[i],num_knn[idx],min(idx//4+1,max_dilation),conv, act, norm,
                                    bias, stochastic, epsilon, reduce_ratios[i], n=HW, drop_path=drop_path_rate[idx],
                                    relative_pos=True),
                          FFN(channels[i], channels[i] * 4, act=act, drop_path=drop_path_rate[idx])
                         ))
                idx+=1

        self.backbone = Seq(*self.backbone)


        self.prediction = Seq(nn.Conv2d(channels[-1], 1024, 1, bias=True),
                              nn.BatchNorm2d(1024),
                              act_layer(act),
                              nn.Dropout(opt.dropout),
                              nn.Conv2d(1024, opt.n_classes, 1, bias=True))
        self.model_init()
    def model_init(self):
        for m in self.modules():
            if isinstance(m, torch.nn.Conv2d):
                torch.nn.init.kaiming_normal_(m.weight)
                m.weight.requires_grad = True
                if m.bias is not None:
                    m.bias.data.zero_()
                    m.bias.requires_grad = True
    def forward(self,inputs):
        x=self.stem(inputs)+self.pos_embed
        B, C, H, W = x.shape
        for i in range(len(self.backbone)):
            x = self.backbone[i](x)

        x = F.adaptive_avg_pool2d(x, 1)
        return self.prediction(x).squeeze(-1).squeeze(-1)
@register_model
def pvig_ti_224_gelu(pretrained=False, **kwargs):
    class OptInit:
        def __init__(self, num_classes=6, drop_path_rate=0.3, **kwargs):
                self.k = 9 # neighbor num (default:9)
                self.conv = 'sage' # graph conv layer {edge, mr}
                self.act = 'gelu' # activation layer {relu, prelu, leakyrelu, gelu, hswish}
                self.norm = 'batch' # batch or instance normalization {batch, instance}
                self.bias = True # bias of conv layer True or False
                self.dropout = 0.3 # dropout rate
                self.use_dilation = True # use dilated knn or not
                self.epsilon = 0.2 # stochastic epsilon for gcn
                self.use_stochastic = False # stochastic for gcn, True or False
                self.drop_path = drop_path_rate
                self.blocks = [2,2,18,2] # number of basic blocks in the backbone
                self.channels = [128, 256, 512, 1024] # number of channels of deep features
                self.n_classes = num_classes # Dimension of out_channels
                self.emb_dims = 1024 # Dimension of embeddings

    opt = OptInit(**kwargs)
    model = DeepGCN(opt)
    model.default_cfg = default_cfgs['vig_224_gelu']
    return model

In [26]:
import gc
gc.collect()
torch.cuda.empty_cache()

In [27]:
import torch


In [30]:
from GPUtil import showUtilization as gpu_usage
gpu_usage()
def free_gpu_cache():
    print("Initial GPU Usage")
    gpu_usage()

    torch.cuda.empty_cache()

    cuda.select_device(0)
    cuda.close()
    cuda.select_device(0)

    print("GPU Usage after emptying the cache")
    gpu_usage()

free_gpu_cache()

| ID | GPU | MEM |
------------------
|  0 |  4% |  4% |
|  1 |  0% |  0% |
Initial GPU Usage
| ID | GPU | MEM |
------------------
|  0 |  4% |  4% |
|  1 |  0% |  0% |


NameError: name 'cuda' is not defined

In [31]:
import torch
import os
import torch.nn as nn
import numpy as np
from torch.nn.utils import clip_grad_norm
import numpy as np
import pandas as pd
import os
import shutil

In [ ]:
paths='/home/accl/Desktop/borescope-adr-lm2500-data-develop/'
test_csv = pd.read_csv("/home/accl/Desktop/borescope-adr-lm2500-data-develop/dataset_5/dataset5_test_filtered.csv")
test_csv["class_name"] = test_csv["class_name"].str.replace("/", "_")
print(test_csv.head())

FileNotFoundError: [Errno 2] No such file or directory: '/home/accl/Desktop/borescope-adr-lm2500-data-develop/dataset_5/dataset5_test_filtered.csv'

In [ ]:
train_csv = pd.read_csv("/home/accl/Desktop/borescope-adr-lm2500-data-develop/dataset_5/dataset5_train_filtered.csv")
train_csv["class_name"] = train_csv["class_name"].str.replace("/", "_")
print(train_csv.head())

                                    img_name class_name  xmin  ymin  xmax   
0  0ab659c5-308f-4054-b795-b2cd956854f9.jpeg  DENT_NICK   305   171   447  \
1  0ab659c5-308f-4054-b795-b2cd956854f9.jpeg      CRACK   418   161   517   
2  0ab659c5-308f-4054-b795-b2cd956854f9.jpeg  DENT_NICK   464   216   518   
3  0ba75c3a-3d90-4f23-9803-886878805f2e.jpeg   TBC LOSS   205   463   293   
4  0ba75c3a-3d90-4f23-9803-886878805f2e.jpeg   TBC LOSS   340   665   524   

   ymax  
0   229  
1   176  
2   229  
3   488  
4   746  


In [ ]:
import torch
import torchvision.transforms as transforms
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader

# Define data augmentation transformations
data_transforms = transforms.Compose([
    transforms.Resize((224, 224)),

    transforms.RandomRotation(10),
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),

    transforms.ToTensor(),

    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

# Create train and test datasets
path = "/home/accl/Desktop/borescope-adr-lm2500-data-develop/preprocessed"
train_dataset = ImageFolder(root='/home/accl-ros/wo_Dup/train/', transform=data_transforms)
test_dataset = ImageFolder(root='/home/accl-ros/wo_Dup/test/', transform=data_transforms)

# Create data loaders
train_loader = DataLoader(train_dataset, batch_size=40, shuffle=True, num_workers=4)
test_loader = DataLoader(test_dataset, batch_size=30, shuffle=False, num_workers=4)

In [ ]:
len(train_loader)

98

In [ ]:
def check_balance(train_loader):
    class_count = {}
    for _, labels in train_loader:
        for label in labels:
            if label.item() not in class_count:
                class_count[label.item()] = 0
            class_count[label.item()] += 1
    print(check_balance)
    return(class_count)

# Assume you have a DataLoader object named train_loader
class_count=check_balance(train_loader)


<function check_balance at 0x7f880ddb91b0>


In [ ]:
class_count

{3: 662, 4: 1053, 1: 667, 2: 955, 0: 447, 5: 101}

In [ ]:
!pip install albumentations



In [ ]:
from torch.utils.data import random_split

In [ ]:
from torch.utils.data import DataLoader, ConcatDataset, Subset
from torchvision import transforms
from torch.utils.data import random_split

# Define data augmentation transformations for imbalance mitigation
imbalance_transforms = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(20),
    transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1),

    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
])

# Set the target number of samples per class
target_samples_per_class = max(class_count.values())

# Separate the indices of samples from each class
indices_per_class = {i: [] for i in class_count.keys()}
for idx, (_, label) in enumerate(train_dataset):
    indices_per_class[label].append(idx)

# Initialize a list to hold the balanced datasets
datasets = []

# Iterate over each class
for class_label, indices in indices_per_class.items():
    # Calculate the number of extra samples needed to reach the target
    extra_samples = target_samples_per_class - len(indices)

    # Create a new subset for the class
    class_subset = Subset(train_dataset, indices)

    # Create transformations for data augmentation
    class_subset.dataset.transform = imbalance_transforms

    # Duplicate the subset the necessary number of times
    class_datasets = [class_subset] * (1 + extra_samples // len(indices))

    # If necessary, add some extra samples to reach the target exactly
    if extra_samples % len(indices) != 0:
        extra_subset = Subset(class_subset, range(extra_samples % len(indices)))
        class_datasets.append(extra_subset)

    # Concatenate the class datasets together
    class_dataset = ConcatDataset(class_datasets)

    # Add the class dataset to the list of datasets
    datasets.append(class_dataset)

# Concatenate all the class datasets together
balanced_dataset = ConcatDataset(datasets)
length = len(balanced_dataset)
train_proportion = 0.85
train_len = int(length * train_proportion)
valid_len = length - train_len
balanced_train_data, balanced_valid_data = random_split(balanced_dataset, [train_len, valid_len])
balanced_train_loader = DataLoader(balanced_train_data, batch_size=230, shuffle=True)
balanced_valid_loader = DataLoader(balanced_valid_data, batch_size=94, shuffle=True)


In [ ]:
len(balanced_train_loader)

24

In [ ]:
f=check_balance(balanced_train_loader)

<function check_balance at 0x7f880ddb91b0>


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import warnings
warnings.filterwarnings('ignore')


device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

#

#

model = pvig_ti_224_gelu(num_classes=6).to(device)
if torch.cuda.device_count() > 1:
  model = nn.DataParallel(model)


criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


import matplotlib.pyplot as plt

train_losses = []
train_accuracies = []

for epoch in range(320):

    running_loss = 0.0
    correct_predictions = 0
    total_predictions = 0
    patience=10
    stop_count = 0
    min_valid_loss = float('inf')
    model.train()

    for i, data in enumerate(balanced_train_loader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data[0].to(device), data[1].to(device)


        optimizer.zero_grad()


        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total_predictions += labels.size(0)
        correct_predictions += (predicted == labels).sum().item()

        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if i % 25== 24:    # print every 200 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 200))
            running_loss = 0.0

    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = 100 * correct_predictions / total_predictions
    train_losses.append(epoch_loss)
    train_accuracies.append(epoch_accuracy)

    print(f'Epoch {epoch+1}, Loss: {epoch_loss}, Accuracy: {epoch_accuracy}%')
    model.eval()
    valid_loss = 0.0
    for i, data in enumerate(balanced_valid_loader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data[0].to(device), data[1].to(device)


        optimizer.zero_grad()


        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total_predictions += labels.size(0)
        correct_predictions += (predicted == labels).sum().item()

        loss = criterion(outputs, labels)
        valid_loss += loss.item()
    valid_loss /= len(balanced_valid_loader.dataset)

    print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, 500, valid_loss))

    # Check for Early Stopping
    if valid_loss < min_valid_loss:
        min_valid_loss = valid_loss
        stop_count = 0
    else:
        stop_count += 1
        if stop_count >= patience:
            print("Early stopping")
            break

print('Finished Training')
torch.save({
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
}, 'model_checkpoint.pth')


# Now let's plot the training loss and accuracy
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(train_losses, 'r-', label='Train Loss')
plt.title('Training Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(train_accuracies, 'g-', label='Train Accuracy')
plt.title('Training Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

<__main__.pvig_ti_224_gelu.<locals>.OptInit object at 0x7f8808c6f3d0>
using relative pos
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31.]
[1.00000000e+00 7.49894209e-01 5.62341325e-01 4.21696503e-01
 3.16227766e-01 2.37137371e-01 1.77827941e-01 1.33352143e-01
 1.00000000e-01 7.49894209e-02 5.62341325e-02 4.21696503e-02
 3.16227766e-02 2.37137371e-02 1.77827941e-02 1.33352143e-02
 1.00000000e-02 7.49894209e-03 5.62341325e-03 4.21696503e-03
 3.16227766e-03 2.37137371e-03 1.77827941e-03 1.33352143e-03
 1.00000000e-03 7.49894209e-04 5.62341325e-04 4.21696503e-04
 3.16227766e-04 2.37137371e-04 1.77827941e-04 1.33352143e-04]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.00000000e+00 7.49894209e-01 5.62341325e-01 ... 2.37137371e-04
  1.77827941e-04 1.33352143e-04]
 [2.00000000e+00 1.49978842e+00 1.12468265e+00 ... 4.74274741e-04
  3.55655882e-04 2.66704286

OutOfMemoryError: Caught OutOfMemoryError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/accl-ros/.local/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/accl-ros/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/ipykernel_91125/4243268443.py", line 87, in forward
    x = self.backbone[i](x)
  File "/home/accl-ros/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/accl-ros/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/accl-ros/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/ipykernel_91125/102958772.py", line 21, in forward
    x = self.fc2(x)
  File "/home/accl-ros/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/accl-ros/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/accl-ros/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/accl-ros/.local/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/home/accl-ros/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 2450, in batch_norm
    return torch.batch_norm(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 178.00 MiB (GPU 0; 23.67 GiB total capacity; 21.17 GiB already allocated; 65.62 MiB free; 21.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import warnings
warnings.filterwarnings('ignore')


device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

#

#
# Define the model
model = pvig_ti_224_gelu(num_classes=6).to(device)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training the model
import matplotlib.pyplot as plt

train_losses = []
train_accuracies = []

#for epoch in range(300):  # loop over the dataset multiple times

    running_loss = 0.0
    correct_predictions = 0
    total_predictions = 0

    for i, data in enumerate(balanced_train_loader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data[0].to(device), data[1].to(device)


        optimizer.zero_grad()


        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total_predictions += labels.size(0)
        correct_predictions += (predicted == labels).sum().item()

        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if i % 25== 24:    # print every 200 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 200))
            running_loss = 0.0

    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = 100 * correct_predictions / total_predictions
    train_losses.append(epoch_loss)
    train_accuracies.append(epoch_accuracy)

    print(f'Epoch {epoch+1}, Loss: {epoch_loss}, Accuracy: {epoch_accuracy}%')

print('Finished Training')
torch.save({
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
}, 'model_checkpoint.pth')


# Now let's plot the training loss and accuracy
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(train_losses, 'r-', label='Train Loss')
plt.title('Training Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(train_accuracies, 'g-', label='Train Accuracy')
plt.title('Training Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.show()

IndentationError: unexpected indent (814785529.py, line 30)

In [ ]:
class_count_test=check_balance(test_loader)
class_count_test

<function check_balance at 0x7f6eb8a8a950>


{0: 59, 1: 98, 2: 109, 3: 30, 4: 77, 5: 9}

In [ ]:
from torch.utils.data import DataLoader, ConcatDataset, Subset
from torchvision import transforms


target_samples_per_class_test = max(class_count_test.values())


indices_per_class_test = {i: [] for i in class_count.keys()}
for idx, (_, label) in enumerate(test_dataset):
    indices_per_class_test[label].append(idx)


datasets_test = []


for class_label, indices in indices_per_class_test.items():
    # Calculate the number of extra samples needed to reach the target
    extra_samples = target_samples_per_class_test - len(indices)


    class_subset = Subset(test_dataset, indices)


    transform = transform = transforms.Compose([
    transforms.Resize((224, 224)),
  # Resize all images to 64x64
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(20),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,)),
])



    class_subset.dataset.transform = transform


    class_datasets = [class_subset] * (1 + extra_samples // len(indices))


    if extra_samples % len(indices) != 0:
        extra_subset = Subset(class_subset, range(extra_samples % len(indices)))
        class_datasets.append(extra_subset)

    # Concatenate the class datasets together
    class_dataset = ConcatDataset(class_datasets)

    # Add the class dataset to the list of datasets
    datasets_test.append(class_dataset)

# Concatenate all the class datasets together
balanced_dataset_test = ConcatDataset(datasets_test)

# Create a new DataLoader for the balanced dataset
balanced_train_loader_test = DataLoader(balanced_dataset_test, batch_size=36, shuffle=True)

In [ ]:
check_balance(balanced_train_loader_test)

<function check_balance at 0x7f6eb8a8a950>


{2: 109, 0: 109, 3: 109, 5: 109, 4: 109, 1: 109}

In [ ]:
check_balance(ba)

NameError: name 'ba' is not defined

In [ ]:
import torch
from torchvision import datasets, transforms


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


checkpoint = torch.load('model_checkpoint.pth')
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])

model.eval()

correct = 0
total = 0
with torch.no_grad():
    for data in balanced_train_loader_test:
        images, labels = data[0].to(device), data[1].to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print('Accuracy of the network on the test images: %d %%' % (100 * correct / total))

Accuracy of the network on the test images: 62 %
